name: CI

on: [push]

env:
  CC: clang-9
  CXX: clang++-9

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install clang-9
      run: |
        sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
        sudo apt update
        sudo apt install -y clang-9
    - name: modest submodule
      run: git submodule update --init --recursive
    - name: prepare
      run: mkdir build
    - name: cmake
      run: cd build ; cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: make -C build
    - name: test
      run: cd build ; ctest
