name: build

on:
  push:
    paths-ignore:
    - 'doc/**'
  pull_request:
    paths-ignore:
    - 'doc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cxx: [g++-9, clang++-10]
    steps:
    - uses: actions/checkout@v1
    - name: install compilers
      run: |
        sudo apt update
        sudo apt install -y g++-9
        sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
        sudo apt update
        sudo apt install -y clang-10
    - name: update modest submodule
      run: git submodule update --init --recursive
    - name: prepare
      run: mkdir build
    - name: cmake
      env:
        CXX:
          ${{ matrix.cxx }}
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: make -C build
    - name: test
      run: |
        cd build
        ctest
