name: build

on:
  push:
    paths-ignore:
    - 'doc/**'
  pull_request:
    paths-ignore:
    - 'doc/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cxx: [g++-9, clang++-9]
    steps:
    - uses: actions/checkout@v1
    - name: install compilers
      run: |
        sudo apt update
        sudo apt install -y gcc-9
        sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
        sudo apt update
        sudo apt install -y clang-9
    - name: update modest submodule
      run: git submodule update --init --recursive
    - name: prepare
      run: mkdir build
    - name: cmake
      env:
        CXX:
          ${{ matrix.cxx }}
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: make -C build
    - name: test
      run: |
        cd build
        ctest
